---
- hosts: web
  become: yes
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Iniciar servicio Nginx
      service:
        name: nginx
        state: started
        enabled: yes