version: '3.8'

services:
  web:
    build: ./app
    container_name: miapp
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=taskdb
      - DB_USER=postgres
      - DB_PASS=postgres
    networks:
      - frontend
      - backend
    links:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: andres@domain.com
      PGADMIN_DEFAULT_PASSWORD: andres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - frontend
      - backend
    links:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taskdb" ]
      interval: 5s
      timeout: 20s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend



volumes:
  pgdata:
  pgadmin_data:

networks:
  frontend:
    # Specify driver options
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend:
    # Use a custom driver
    driver: bridge
