global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      # Node Exporter expuesto en el host (9100)
      - targets: ['host.docker.internal:9100']   # mac/windows
        labels: { instance: 'host-node' }
      - targets: ['prometheus:9100']              # linux (si no resolviera host.docker.internal)
        labels: { instance: 'host-node' }

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']