---
- name: Instalar nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Plantilla de index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reiniciar nginx
  become: yes

- name: Asegurar servicio
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes