apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080