apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: devops-lab
  labels: { app: rabbit }
spec:
  replicas: 1
  selector:
    matchLabels: { app: rabbit }
  template:
    metadata:
      labels: { app: rabbit }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          readinessProbe:
            tcpSocket: { port: 5672 }
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: devops-lab
spec:
  selector: { app: rabbit }
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: ui
      port: 15672
      targetPort: 15672
      # (opcional) NodePort para UI:
      # nodePort: 31672
  type: ClusterIP