apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: proyecto-final
type: Opaque
stringData:
  POSTGRES_USER: labuser
  POSTGRES_PASSWORD: labpass
  POSTGRES_DB: labdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: proyecto-final
data:
  CELERY_BROKER_URL: amqp://guest:guest@rabbit:5672//
  CELERY_RESULT_BACKEND: redis://redis:6379/0