apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: proyecto-final
  labels: { app: api }
spec:
  replicas: 2
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: andrs/flaskapi:5.0
          #image: usuario/flaskapi:1.0   # <-- pon tu imagen
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_DB } }
            - name: CELERY_BROKER_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: CELERY_BROKER_URL } }
            - name: CELERY_RESULT_BACKEND
              valueFrom: { configMapKeyRef: { name: app-config, key: CELERY_RESULT_BACKEND } }
          envFrom:
            - configMapRef: { name: app-config }
          readinessProbe:
            httpGet: { path: /ping, port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /ping, port: 5000 }
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: proyecto-final
spec:
  selector: { app: api }
  ports:
    - port: 80
      targetPort: 5000