---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: proyecto-final
spec:
  selector: { app: api }
  ports:
    - port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: proyecto-final
spec:
  selector: { app: db }
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: proyecto-final
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: postgres:15
          envFrom:
            - secretRef: { name: db-secret }
          command: ["sh","-lc"]
          args:
            - |
              until pg_isready -h db -U "$POSTGRES_USER"; do sleep 2; done
              psql -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "
                CREATE TABLE IF NOT EXISTS resultados (
                  id SERIAL PRIMARY KEY,
                  x INT NOT NULL,
                  y INT NOT NULL,
                  resultado INT NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );"
---